version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ENV=local
      - ENV_PORT=9080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/cultere_events
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
    ports:
      - "9080:9080"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: cultere_events
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"